#!/usr/bin/env bash
# Interactive Setup Script for Knowledge Base Tool

echo "=================================================="
echo "    Knowledge Base Tool - Initial Setup"
echo "=================================================="
echo ""

ENV_FILE="dockerise/.env"

# Prompt for Sync Folder
SYNC_INPUT=""

# Check if on macOS
if [[ "$OSTYPE" == "darwin"* ]]; then
    echo "🍎 macOS detected! Would you like to automatically use iCloud Drive for your Sync folder?"
    echo "(Path: ~/Library/Mobile Documents/com~apple~CloudDocs/KnowledgeBase_Sync)"
    read -p "Use iCloud Drive? (y/N): " USE_ICLOUD
    if [[ "$USE_ICLOUD" =~ ^[Yy]$ ]]; then
        SYNC_INPUT="~/Library/Mobile Documents/com~apple~CloudDocs/KnowledgeBase_Sync"
        echo "✅ Selected iCloud Drive for Sync."
    fi
fi

if [ -z "$SYNC_INPUT" ]; then
    echo ""
    echo "Where would you like your main Sync folder to be?"
    echo "(e.g., /Users/yourname/Google Drive/KBSync, or press Enter for default: ./kb_sync)"
    read -p "Sync Path: " SYNC_INPUT
fi

if [ -z "$SYNC_INPUT" ]; then
    SYNC_DIR="$(pwd)/kb_sync"
else
    # Expand tilde ~ to full home directory path if used
    SYNC_DIR="${SYNC_INPUT/#\~/$HOME}"
fi

# Prompt for Backup Folder
BACKUP_INPUT=""
SYNC_PARENT=$(dirname "$SYNC_DIR")
SUGGESTED_BACKUP="$SYNC_PARENT/KnowledgeBase_Backup"

echo ""
read -p "Would you like to create a Backup folder in the same location as your Sync folder? ($SUGGESTED_BACKUP) (y/N): " USE_SAME_LOC
if [[ "$USE_SAME_LOC" =~ ^[Yy]$ ]]; then
    BACKUP_INPUT="$SUGGESTED_BACKUP"
    echo "✅ Selected Backup folder."
else
    echo ""
    echo "Where would you like your Backup folder to be?"
    echo "(e.g., /Users/yourname/Backups/KB, or press Enter for default: ./kb_backup)"
    read -p "Backup Path: " BACKUP_INPUT
fi

if [ -z "$BACKUP_INPUT" ]; then
    BACKUP_DIR="$(pwd)/kb_backup"
else
    # Expand tilde ~ to full home directory path if used
    BACKUP_DIR="${BACKUP_INPUT/#\~/$HOME}"
fi

# Create directories if they don't exist
echo ""
echo "Creating directories if they don't exist..."
mkdir -p "$SYNC_DIR"
mkdir -p "$BACKUP_DIR"
echo "✅ Directories ready."

# Write to .env file
echo ""
echo "Saving configuration to $ENV_FILE..."
cat << EOF > $ENV_FILE
# Auto-generated by setup.sh
SYNC_DIR=$SYNC_DIR
BACKUP_DIR=$BACKUP_DIR
EOF
echo "✅ Configuration saved."

# Remind user to set paths in the app UI
echo ""
echo "=================================================="
echo "   ⚠️ IMPORTANT NEXT STEPS AFTER STARTING ⚠️"
echo "=================================================="
echo "Once the app starts, open Settings -> Sync Tab,"
echo "and enter exactly:"
echo "   Sync Folder Path:   /sync"
echo "   Backup Folder Path: /backup"
echo "(Docker internally maps these to your chosen paths)"
echo "=================================================="
echo ""

read -p "Press Enter to build and start Docker..."

# Start Docker
echo "Starting Docker Compose..."
docker compose -f dockerise/docker-compose.yml up --build -d

echo ""
echo "🎉 Setup Complete! The app is running at http://localhost:5050"
